"""Add ON DELETE CASCADE to foreign keys

Revision ID: 049552849be0
Revises: ca57cf4f1da9
Create Date: 2024-11-16 13:30:13.533708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049552849be0'
down_revision = 'ca57cf4f1da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_constraint('fk_places_owner_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_places_owner_id_users', 'users', ['owner_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_place_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_place_id_places', 'places', ['place_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_reviews_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_place_id', 'places', ['place_id'], ['id'])
        batch_op.create_foreign_key('fk_reviews_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_places_owner_id', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###
