"""Renamed amenities relationship to amenities_obj

Revision ID: ca57cf4f1da9
Revises: 13fc9d634dad
Create Date: 2024-11-11 16:53:45.159452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca57cf4f1da9'
down_revision = '13fc9d634dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amenities', sa.JSON(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('owner',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('reviews',
               existing_type=sa.NUMERIC(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_places_owner_id', 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_constraint('fk_places_owner_id', type_='foreignkey')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('reviews',
               existing_type=sa.JSON(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('owner',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('amenities')

    # ### end Alembic commands ###
